package org.bh.tools.base.util

import org.bh.tools.base.math.*
import kotlin.math.*

/**
 * Manages the creation of new unique IDs
 *
 * @author Ben Leggiero
 * @since 2018-03-13
 */
object IdManager {
    private var lastShortIdBasis: Long = 0

    /**
     * Generates a new unique ID that is very short. Note that this will be a runtime-unique ID and not a
     * universally-unique one. For example, `"u"` or `"9c"`.
     */
    fun generateNewShortId(): String {
        val currentShortIdBasis = lastShortIdBasis
        lastShortIdBasis += 1
        return currentShortIdBasis.toBase(baseCharacters = shortIds_v1)
    }

    /**
     * When you are deserializing something that uses an ID generated by [generateNewShortId], you should pass it to
     * this function so that we can ensure new IDs don't conflict with existing ones.
     */
    fun registerEncounteredShortId(encounteredShortId: String) {
        lastShortIdBasis = max(lastShortIdBasis, encounteredShortId.fromBase(baseCharacters = shortIds_v1))
    }
}

private const val shortIds_v1 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_#"
